const books = [
  {
    id: 1,
    author: "Jordan Peterson",
    title: "12 Rules for Life: An Antidote to Chaos",
    slug: "12-rules-for-life:-an-antidote-to-chaos",
    image:
      "https://images-na.ssl-images-amazon.com/images/I/41kspFBwVxL._SX331_BO1,204,203,200_.jpg",
    genre: ["Self-Help"],
    available: false,
    borrowedBy: [3],
  },
  {
    id: 2,
    author: "Blake Crouch",
    title: "Dark Matter",
    slug: "dark-matter",
    image:
      "https://www.scifinow.co.uk/wp-content/uploads/2016/08/DARK-MATTER.jpg",
    genre: ["Sci-Fi", "Thriller"],
    available: false,
    borrowedBy: [3],
  },
  {
    id: 3,
    author: "Robin Sloan",
    title: "Mr. Penumbra's 24-Hour Bookstore",
    slug: "mr.-penumbra's-24-hour-bookstore",
    image: "https://images-na.ssl-images-amazon.com/images/I/71UhnbUOwzL.jpg",
    genre: ["Suspense", "Fantasy"],
    available: false,
    borrowedBy: [1, 3, 5, 1],
  },
  {
    id: 4,
    author: "Paul Kalanithi",
    title: "When Breath Becomes Air",
    slug: "when-breath-becomes-air",
    image: "https://images-na.ssl-images-amazon.com/images/I/91oF75m7gAL.jpg",
    genre: ["Biography"],
    available: true,
    borrowedBy: [2, 5],
  },
  {
    id: 5,
    author: "Eric Ries",
    title: "The Lean Startup",
    slug: "the-lean-startup",
    image: "https://images-na.ssl-images-amazon.com/images/I/81-QB7nDh4L.jpg",
    genre: ["Business", "Entrepreneurship"],
    available: false,
    borrowedBy: [4, 1, 2],
  },
  {
    id: 6,
    author: "George R.R. Martin",
    title: "A Storm of Swords",
    slug: "a-storm-of-swords",
    image: "https://bestsellers.hu/images/item_image/original/66.jpg",
    genre: ["Fantasy"],
    available: true,
    borrowedBy: [],
  },
  {
    id: 7,
    author: "Leigh Bardugo",
    title: "Six of Crows",
    slug: "six-of-crows",
    image: "https://rfbd.hs.llnwd.net/siteContent/bkimages/detail/NA474.jpg",
    genre: ["Fantasy"],
    available: false,
    borrowedBy: [4, 3, 2, 1, 5],
  },
  {
    id: 8,
    author: "Agatha Christie",
    title: "Curtain: Poirot's Last Case",
    slug: "curtain:-poirot's-last-case",
    image:
      "https://strandmag.com/wp-content/uploads/2018/06/Curtain-Poirots-Last-Case-A-Hercule-Poirot-Mystery-by-Agatha-Christie-paperback-.jpeg",
    genre: ["Crime", "Mystery"],
    available: false,
    borrowedBy: [3, 5],
  },
  {
    id: 9,
    author: "Elif Shafak",
    title: "The Forty Rules of Love",
    slug: "the-forty-rules-of-love",
    image: "https://miro.medium.com/max/700/1*XqHIC1QN8VCEcBaHdtWvxg.jpeg",
    genre: ["Fiction"],
    available: false,
    borrowedBy: [5, 1],
  },
  {
    id: 10,
    author: "Leigh Bardugo",
    title: "The Language of Thorns: Midnight Tales and Dangerous Magic",
    slug: "the-language-of-thorns:-midnight-tales-and-dangerous-magic",
    image: "https://images-na.ssl-images-amazon.com/images/I/71UTzR3TitL.jpg",
    genre: ["Fantasy"],
    available: false,
    borrowedBy: [5],
  },
];

export default books;
